version: '3.3'
services:
    transmission-openvpn:
      container_name: transmission
      cap_add:
        - NET_ADMIN
      volumes:
        - '/var/www/html/files/ssd/transmission-data:/data' # mount this folder on sonarr + radarr so they have access to transmission downloads
        - '/var/www/html/files/'
        - '/home/pi/Documents/protonvpn-configs/:/etc/openvpn/custom/'
      environment:
        - OPENVPN_PROVIDER=custom
        - OPENVPN_CONFIG=openvpn file or country name
        - OPENVPN_USERNAME=user
        - OPENVPN_PASSWORD=pass
        - LOCAL_NETWORK=192.168.178.0/24 # change to your subnet
        - TRANSMISSION_RPC_WHITELIST_ENABLED=false
        - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
        - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
        - TRANSMISSION_IDLE_SEEDING_LIMIT=0
        - TRANSMISSION_RATIO_LIMIT=0 # disable seeding
        - TRANSMISSION_RATIO_LIMIT_ENABLED=true
        - TRANSMISSION_SPEED_LIMIT_UP=0 # disable upload speed to completely disable seeding
        - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      logging:
        driver: json-file
        options:
          max-size: 10m
      ports:
        - '9091:9091'
        - '7878:7878'
        - '9117:9117'
        - '8989:8989'
      image: haugene/transmission-openvpn

    radarr:
      network_mode: 'service:transmission-openvpn'
      image: lscr.io/linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=33
        - PGID=33
        - TZ=Europe/Berlin
      volumes:
        - '/var/www/html/files/ssd/radarr-data:/config'
        - '/var/www/html/files/ssd/transmission-data:/data'
        - '/var/www/html/files/ssd/movies:/movies'
      restart: unless-stopped

    sonarr:
      image: linuxserver/sonarr
      network_mode: "service:transmission-openvpn"
      container_name: sonarr
      environment:
        - PUID=33
        - PGID=33
        - TZ=Europe/Berlin
        - UMASK_SET=022 #optional
      volumes:
        - '/var/www/html/files/ssd/sonarr-data:/config'
        - '/var/www/html/files/ssd/transmission-data:/data'
        - '/var/www/html/files/ssd/shows:/shows'
      restart: unless-stopped

    jackett:
      network_mode: 'service:transmission-openvpn'
      image: lscr.io/linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=33
        - PGID=33
        - TZ=Europe/Berlin
        - AUTO_UPDATE=true #optional
        #- RUN_OPTS=
      volumes:
        - '/var/www/html/files/ssd/jackett-data:/config'
        - '/var/www/html/files/ssd/jackett-blackhole:/downloads'
      restart: unless-stopped
