version: '3.3'
networks:
  eth0:
services:
    transmission-openvpn:
      container_name: transmission
      devices:
        - /dev/net/tun
      cap_add:
        - NET_ADMIN
      volumes:
        - '/home/user/ssd/transmission-data:/data' #edit
        - '/home/user/ssd/transmission-data/transmission-home/:/config' #edit
      sysctls:
        - "net.ipv6.conf.all.disable_ipv6=0"
      environment:
        - OPENVPN_PROVIDER=
        - OPENVPN_USERNAME=
        - OPENVPN_PASSWORD=
        - LOCAL_NETWORK=192.168.2.0/24
        - TRANSMISSION_RPC_WHITELIST_ENABLED=false
        - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
        - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
        - TRANSMISSION_IDLE_SEEDING_LIMIT=0
        - TRANSMISSION_RATIO_LIMIT=0
        - TRANSMISSION_RATIO_LIMIT_ENABLED=true
        - TRANSMISSION_SPEED_LIMIT_UP=0
        - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      logging:
        driver: json-file
        options:
          max-size: 10m
      networks:
        - eth0
      ports:
        - '9091:9091' # transmission
        - '7878:7878' # radarr
        - '8989:8989' # sonarr
        - '9696:9696' # prowlarr
        - '8191:8191' # flaresolverr
        - '8080:8080' # neko
        - '5055:5055' # jellyseerr
      image: haugene/transmission-openvpn
      restart: unless-stopped

    radarr:
      network_mode: 'service:transmission-openvpn'
      image: lscr.io/linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - UMASK=002
      volumes:
        - '/home/user/arr-data/radarr-data:/config' #edit
        - '/home/user/ssd/transmission-data:/data' #edit
        - '/home/user/ssd/movies:/movies' #edit
      restart: unless-stopped

    sonarr:
      image: linuxserver/sonarr
      network_mode: 'service:transmission-openvpn'
      container_name: sonarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - UMASK=002
      volumes:
        - '/home/user/arr-data/sonarr-data:/config' #edit
        - '/home/user/ssd/transmission-data:/data' #edit
        - '/home/user/ssd/shows:/shows' #edit
      restart: unless-stopped

    flaresolverr:
      network_mode: 'service:transmission-openvpn'
      image: ghcr.io/flaresolverr/flaresolverr:latest
      container_name: flaresolverr
      restart: unless-stopped

    prowlarr:
      network_mode: 'service:transmission-openvpn'
      image: lscr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
      volumes:
        - '/home/user/arr-data/prowlarr-data:/config' #edit
      restart: unless-stopped

    jellyseerr:
      image: fallenbagel/jellyseerr:latest
      network_mode: 'service:transmission-openvpn'
      profiles:
        - media
      container_name: jellyseerr
      environment:
        - LOG_LEVEL=debug
        - TZ=Europe/Berlin
        - PORT=5055 #optional
      volumes:
        - '/home/user/arr-data/jellyseerr:/app/config'
      restart: unless-stopped
